[project]
name = "curso-ia-deveficiente"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docling>=2.76.0",
    "edgartools>=5.30.1",
    "groq>=1.0.0",
    "hdbscan>=0.8.41",
    "langextract>=1.1.1",
    "nltk>=3.9.2",
    "numpy>=2.4.2",
    "openai>=2.24.0",
    "openapi>=2.0.0",
    "pydentic>=0.0.1.dev3",
    "python-dotenv>=1.2.2",
    "qdrant-client[fastembed]>=1.17.0",
    "rank-bm25>=0.2.2",
    "ruff>=0.15.12",
    "scikit-learn>=1.8.0",
    "sentence-transformers>=5.2.3",
    "whoosh>=2.7.4",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
